#!/bin/bash

# get number of protocol ( + leading "1" to avoid the reduce of 00001 => 1
number=`ls /var/log/vsftpd.log-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]* 2> /dev/null | tail -1 | xargs gzip -dc |perl -pe 's/^.*vsftpd.log-.(\d*)/\1/' `

echo $number

pfile=/var/log/vsftp.log-`echo $number`

tail -f $pfile &

CHILD=$!
let number=number+1
pfile=/var/log/vsftpd.log-`echo $number`

trap 'kill -TERM $CHILD ; exit 0' 1 2 3 15

while true
do
	sleep 1
	#check if new number exists
	if [ -s $pfile ]
	then
		kill -TERM $CHILD
		tail -f $pfile &
		CHILD=$!
		let number=number+1
		pfile=/var/log/vsftpd.log-`echo $number`
	fi	
        ps -p $CHILD > /dev/null
        if [ $? -ne 0 ]
        then
                #echo Child dead 1>&2
                exit 0
        fi

done
